# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(choices=[('中国', '中国'), ('其他', '其他')], max_length=6)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=6)),
                ('attribute', models.CharField(choices=[('金', '金'), ('木', '木'), ('水', '水'), ('火', '火'), ('土', '土')], default='金', max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
